query GetAllProducts {
  products(order_by: { created_at: desc }) {
    id
    name
    image
    discount
    brand
    sizes
    stock
    is_new
    ratings
    seller
    price
    image_gallery
    created_at
    updated_at
  }
}
