query GetSingleProduct {
  products(where: { id: { _eq: 2 } }) {
    id
    name
    image
    discount
    brand
    sizes
    stock
    is_new
    ratings
    seller
    price
    image_gallery
    created_at
    updated_at
  }
}
